import { describe, expect, test } from "bun:test"
import { mkdtemp, readFile, rm, writeFile } from "node:fs/promises"
import { tmpdir } from "node:os"
import { join } from "node:path"
import { Effect, Redacted, Stream } from "effect"
import { defaultConfig } from "./Config.ts"
import type { DiscordGatewayClient, DiscordGatewayOptions } from "./Discord/DiscordGateway.ts"
import { DiscordError, type DiscordService } from "./Discord/DiscordPort.ts"
import { makeMemoryDiscord } from "./Discord/MemoryDiscord.ts"
import { liveRuntimeFactories, makeApplication, makeProgram, type RuntimeFactories } from "./Main.ts"
import { makeMemoryOpencode } from "./Opencode/MemoryOpencode.ts"
import { OpencodeError, type OpencodeService } from "./Opencode/OpencodePort.ts"
import type { DiscordMessage } from "./Schema.ts"

const makeFakeGatewayClient = (): DiscordGatewayClient => {
  const client: DiscordGatewayClient = {
    user: { id: "self" },
    application: { commands: { create: () => Promise.resolve({}) } },
    channels: { fetch: () => Promise.resolve(null) },
    on: () => client,
    once: () => client,
    login: () => Promise.resolve("token"),
    destroy: () => Promise.resolve()
  }
  return client
}

const mentionMessage = {
  id: "m1",
  guildId: "g1",
  channelId: "c1",
  author: { id: "u1", displayName: "Alice", isBot: false },
  content: "hello <@self>",
  timestamp: "2026-06-05T14:03:00.000Z",
  mentions: ["self"],
  roleMentions: [],
  everyoneMention: false,
  hereMention: false,
  attachments: [],
  reactions: [],
  channelType: "guild"
} satisfies DiscordMessage

const makeTestEnv = (projectDir: string, bridgePort: number) => ({
  DISCORD_TOKEN: "token",
  OPENCODE_PROJECT_DIR: projectDir,
  DISCORD_BRIDGE_PORT: bridgePort.toString()
})

describe("makeProgram", () => {
  test("runs Bun preflight, loads config, and scaffolds generated Discord tools", async () => {
    const projectDir = await mkdtemp(join(tmpdir(), "ocdb-program-"))
    const discord = makeMemoryDiscord()
    const opencode = makeMemoryOpencode([])
    const factories: RuntimeFactories = {
      makeDiscord: () => discord,
      makeOpencode: () => opencode,
      startGateway: () => Effect.succeed({ bot: { userId: "self" }, client: makeFakeGatewayClient() }),
      keepAlive: Effect.void
    }

    try {
      await Effect.runPromise(makeProgram(projectDir, makeTestEnv(projectDir, 18_787), factories))
      const tool = await readFile(join(projectDir, ".opencode", "tools", "discord-bridge.ts"), "utf8")

      expect(tool).toContain("Generated by opencode-discord-bot")
      expect(tool).toContain("http://127.0.0.1:18787/tool")
    } finally {
      await rm(projectDir, { recursive: true, force: true })
    }
  })
})

describe("makeApplication", () => {
  test("starts the loopback server through the application facade", async () => {
    const app = makeApplication({
      bot: { userId: "self" },
      config: defaultConfig,
      discord: makeMemoryDiscord(),
      opencode: makeMemoryOpencode([])
    })

    const server = await Effect.runPromise(app.startLoopback(0).pipe(Effect.scoped))

    expect(server.url).toStartWith("http://127.0.0.1:")
    expect(server.port).toBeGreaterThan(0)
  })
})

describe("liveRuntimeFactories", () => {
  test("constructs live opencode through runtime factories", () => {
    expect(liveRuntimeFactories.makeOpencode(defaultConfig)).toBeDefined()
  })
})

describe("makeApplication startup", () => {
  test("reports application start scaffolding failures", async () => {
    const projectDir = await mkdtemp(join(tmpdir(), "ocdb-start-fail-"))
    const blockedPath = join(projectDir, "blocked")
    await writeFile(blockedPath, "not a directory")
    const app = makeApplication({
      bot: { userId: "self" },
      config: { ...defaultConfig, opencode: { ...defaultConfig.opencode, projectDir: blockedPath } },
      discord: makeMemoryDiscord(),
      opencode: makeMemoryOpencode([])
    })

    try {
      await expect(Effect.runPromise(app.start)).rejects.toBeDefined()
    } finally {
      await rm(projectDir, { recursive: true, force: true })
    }
  })

  test("swallows failed message turns from gateway dispatch", async () => {
    const failingDiscord: DiscordService = {
      fetchContext: () => Effect.fail(new DiscordError({ message: "context failed" })),
      fetchHistory: () => Effect.succeed([]),
      sendTyping: () => Effect.void,
      postMessage: () => Effect.succeed({ id: "posted" }),
      editMessage: () => Effect.void,
      addReaction: () => Effect.void,
      removeReaction: () => Effect.void,
      attachFile: () => Effect.succeed({ path: "out.txt" }),
      createThread: () => Effect.succeed({ id: "thread" }),
      deleteMessage: () => Effect.void,
      pinMessage: () => Effect.void,
      unpinMessage: () => Effect.void
    }
    const app = makeApplication({
      bot: { userId: "self" },
      config: defaultConfig,
      discord: failingDiscord,
      opencode: makeMemoryOpencode([])
    })

    await expect(Effect.runPromise(app.startMessageTurn(mentionMessage))).resolves.toBeUndefined()
    await new Promise((resolve) => setTimeout(resolve, 0))
  })
})

describe("makeProgram callbacks", () => {
  test("routes gateway callbacks through the initialized application", async () => {
    const projectDir = await mkdtemp(join(tmpdir(), "ocdb-callbacks-"))
    const discord = makeMemoryDiscord({ context: [mentionMessage] })
    const opencode = makeMemoryOpencode([{ type: "text-delta", text: "callback ok" }, { type: "idle" }])
    let gatewayOptions: DiscordGatewayOptions | undefined
    const factories: RuntimeFactories = {
      makeDiscord: () => discord,
      makeOpencode: () => opencode,
      startGateway: (options) =>
        Effect.sync(() => {
          gatewayOptions = options
          return { bot: { userId: "self" }, client: makeFakeGatewayClient() }
        }),
      keepAlive: Effect.void
    }

    try {
      await Effect.runPromise(makeProgram(projectDir, makeTestEnv(projectDir, 18_788), factories))
      if (gatewayOptions === undefined) throw new Error("gateway options were not captured")

      await Effect.runPromise(gatewayOptions.onMessage(mentionMessage, { userId: "self" }))
      await new Promise((resolve) => setTimeout(resolve, 0))
      await Effect.runPromise(gatewayOptions.onStop({ guildId: "g1", channelId: "c1" }, { userId: "self" }))

      expect(opencode.prompts).toHaveLength(1)
      expect(discord.messages.map((item) => item.content)).toContain("callback ok")
    } finally {
      await rm(projectDir, { recursive: true, force: true })
    }
  })
})

describe("makeApplication facade", () => {
  test("handles Discord tool requests through the application facade", async () => {
    const discord = makeMemoryDiscord({ context: [mentionMessage] })
    let releaseTurn: (() => void) | undefined
    const waiting = new Promise<void>((resolve) => {
      releaseTurn = resolve
    })
    const opencode: OpencodeService = {
      checkHealth: Effect.void,
      abort: () => Stream.empty,
      runPrompt: () =>
        Stream.fromAsyncIterable(
          (async function* () {
            await waiting
            yield { type: "idle" as const }
          })(),
          () => new OpencodeError({ message: "stream failed" })
        )
    }
    const app = makeApplication({
      bot: { userId: "self" },
      config: defaultConfig,
      discord,
      opencode
    })

    const running = Effect.runPromise(app.handleMessage(mentionMessage))
    await new Promise((resolve) => setTimeout(resolve, 0))
    const response = await Effect.runPromise(
      app.handleTool({
        action: "addReaction",
        target: { guildId: "g1", channelId: "c1", messageId: "m1" },
        args: { emoji: "rocket" }
      })
    )
    releaseTurn?.()
    await running

    expect(response).toEqual({ ok: true, result: { reacted: true } })
    expect(discord.reactions).toEqual([{ scope: { guildId: "g1", channelId: "c1" }, messageId: "m1", emoji: "rocket", op: "add" }])
    expect(discord.messages).toEqual([])
  })

  test("runs message turns and stop commands through the application facade", async () => {
    const discord = makeMemoryDiscord({
      context: [
        {
          id: "m1",
          guildId: "g1",
          channelId: "c1",
          author: { id: "u1", displayName: "Alice", isBot: false },
          content: "hello <@self>",
          timestamp: "2026-06-05T14:03:00.000Z",
          mentions: ["self"],
          roleMentions: [],
          everyoneMention: false,
          hereMention: false,
          attachments: [],
          reactions: [],
          channelType: "guild"
        }
      ]
    })
    const opencode = makeMemoryOpencode([{ type: "text-delta", text: "ok" }, { type: "idle" }])
    const app = makeApplication({
      bot: { userId: "self" },
      config: defaultConfig,
      discord,
      opencode
    })
    const trigger = discord.context[0]
    if (trigger === undefined) throw new Error("missing trigger fixture")

    await Effect.runPromise(app.startMessageTurn(trigger))
    await new Promise((resolve) => setTimeout(resolve, 0))
    await Effect.runPromise(app.handleStop({ guildId: "g1", channelId: "c1" }))

    expect(discord.messages.map((item) => item.content)).toEqual(["ok", "There is no known active turn in this process."])
    expect(opencode.aborted).toEqual([])
  })
})

describe("liveRuntimeFactories Discord", () => {
  test("uses chat-sdk Discord when production config includes a public key", () => {
    const service = liveRuntimeFactories.makeDiscord(
      { bot: { userId: "app-1" }, client: makeFakeGatewayClient() },
      {
        ...defaultConfig,
        discordToken: Redacted.make("token"),
        discord: { applicationId: "app-1", publicKey: "0".repeat(64) }
      }
    )

    expect(service).toBeDefined()
  })

  test("uses chat-sdk Discord output even when no public key is configured", () => {
    const service = liveRuntimeFactories.makeDiscord(
      { bot: { userId: "app-1" }, client: makeFakeGatewayClient() },
      { ...defaultConfig, discordToken: Redacted.make("token") }
    )

    expect(service).toBeDefined()
  })
})
