import { mkdir, readFile, writeFile } from "node:fs/promises"
import { join } from "node:path"

const header = "// Generated by opencode-discord-bot. DO NOT EDIT."
const loopbackUrlPattern = /const loopbackToolUrl = "(http:\/\/127\.0\.0\.1:\d+)\/tool"/

export type ToolScaffoldOptions = {
  readonly projectDir: string
  readonly bridgePort: number
  readonly enabled: boolean
  readonly autoInstall: boolean
}

export const renderDiscordToolFile = (loopbackUrl: string): string => `${header}
const loopbackToolUrl = "${loopbackUrl}/tool"

export const description = "Perform safe Discord bridge actions through the local opencode-discord-bot process."

export const parameters = {
  type: "object",
  properties: {
    action: { type: "string" },
    target: { type: "object" },
    args: { type: "object" }
  },
  required: ["action", "target", "args"]
}

export async function execute(input: { action: string; target: object; args: object }) {
  const response = await fetch(loopbackToolUrl, {
    method: "POST",
    headers: { "content-type": "application/json" },
    body: JSON.stringify(input)
  })
  return await response.json()
}
`

const generatedLoopbackUrl = (source: string): string | undefined => loopbackUrlPattern.exec(source)?.[1]

export const ensureDiscordTools = async (options: ToolScaffoldOptions): Promise<ReadonlyArray<string>> => {
  if (!options.enabled || !options.autoInstall) return []
  const toolsDir = join(options.projectDir, ".opencode", "tools")
  const toolPath = join(toolsDir, "discord-bridge.ts")
  const next = renderDiscordToolFile(`http://127.0.0.1:${options.bridgePort}`)

  await mkdir(toolsDir, { recursive: true })
  try {
    const current = await readFile(toolPath, "utf8")
    if (!current.startsWith(header)) return []
    if (current === next) return [toolPath]
    const currentLoopbackUrl = generatedLoopbackUrl(current)
    if (currentLoopbackUrl === undefined || current !== renderDiscordToolFile(currentLoopbackUrl)) return []
  } catch (error) {
    if (!(error instanceof Error) || !Reflect.has(error, "code")) throw error
  }

  await writeFile(toolPath, next)
  return [toolPath]
}
