import { describe, expect, test } from "bun:test"
import { mkdir, mkdtemp, readFile, rm, writeFile } from "node:fs/promises"
import { tmpdir } from "node:os"
import { join } from "node:path"
import { ensureDiscordTools, renderDiscordToolFile } from "./Scaffolding.ts"

describe("Discord tool scaffolding", () => {
  test("renders a generated opencode tool file with the injected loopback URL", async () => {
    const source = await renderDiscordToolFile("http://127.0.0.1:8787")

    expect(source).toContain("Generated by opencode-discord-bot")
    expect(source).toContain("http://127.0.0.1:8787/tool")
    expect(source).toContain('import { tool } from "@opencode-ai/plugin"')
    expect(source).toContain("export default tool({")
    expect(source).toContain("args: {")
    expect(source).toContain(".enum([")
    expect(source).toContain('"fetchHistory"')
    expect(source).toContain('"addReaction"')
    expect(source).toContain(".record(tool.schema.string(), tool.schema.unknown())")
    expect(source).toContain("fetch")
    expect(source).not.toContain("export const parameters")
    expect(source).not.toContain("__OPENCODE_DISCORD_BOT_LOOPBACK_URL__")
  })

  test("creates and regenerates the tool file on every run", async () => {
    const projectDir = await mkdtemp(join(tmpdir(), "ocdb-tools-"))

    try {
      const created = await ensureDiscordTools({ projectDir, bridgePort: 8787, enabled: true, autoInstall: true })
      const toolPath = join(projectDir, ".opencode", "tools", "discord-bridge.ts")
      const first = await readFile(toolPath, "utf8")

      expect(created).toEqual([toolPath])
      expect(first).toContain("http://127.0.0.1:8787/tool")

      await ensureDiscordTools({ projectDir, bridgePort: 9999, enabled: true, autoInstall: true })
      expect(await readFile(toolPath, "utf8")).toContain("http://127.0.0.1:9999/tool")

      await writeFile(toolPath, "// operator file\n")
      const regenerated = await ensureDiscordTools({ projectDir, bridgePort: 7777, enabled: true, autoInstall: true })

      expect(regenerated).toEqual([toolPath])
      expect(await readFile(toolPath, "utf8")).toContain("http://127.0.0.1:7777/tool")
      expect(await readFile(toolPath, "utf8")).not.toContain("// operator file")

      await writeFile(toolPath, "// Generated by opencode-discord-bot. DO NOT EDIT.\nexport const parameters = {}\n")
      const migrated = await ensureDiscordTools({ projectDir, bridgePort: 6666, enabled: true, autoInstall: true })

      expect(migrated).toEqual([toolPath])
      expect(await readFile(toolPath, "utf8")).toContain("http://127.0.0.1:6666/tool")
      expect(await readFile(toolPath, "utf8")).not.toContain("export const parameters")
    } finally {
      await rm(projectDir, { recursive: true, force: true })
    }
  })

  test("does nothing when auto install is disabled", async () => {
    const projectDir = await mkdtemp(join(tmpdir(), "ocdb-tools-disabled-"))

    try {
      await mkdir(join(projectDir, ".opencode"), { recursive: true })
      expect(await ensureDiscordTools({ projectDir, bridgePort: 8787, enabled: true, autoInstall: false })).toEqual([])
    } finally {
      await rm(projectDir, { recursive: true, force: true })
    }
  })
})
