import { mkdir, readFile, writeFile } from "node:fs/promises"
import { join } from "node:path"

const header = "// Generated by opencode-discord-bot. DO NOT EDIT."
const loopbackUrlPlaceholder = "__OPENCODE_DISCORD_BOT_LOOPBACK_URL__"
const discordToolSourceUrl = new URL("./DiscordBridgeTool.ts", import.meta.url)

export type ToolScaffoldOptions = {
  readonly projectDir: string
  readonly bridgePort: number
  readonly enabled: boolean
  readonly autoInstall: boolean
}

export const renderDiscordToolFile = async (loopbackUrl: string): Promise<string> => {
  const source = await readFile(discordToolSourceUrl, "utf8")
  return `${header}\n${source.replaceAll(loopbackUrlPlaceholder, loopbackUrl)}`
}

export const ensureDiscordTools = async (options: ToolScaffoldOptions): Promise<ReadonlyArray<string>> => {
  if (!options.enabled || !options.autoInstall) return []
  const toolsDir = join(options.projectDir, ".opencode", "tools")
  const toolPath = join(toolsDir, "discord-bridge.ts")
  const next = await renderDiscordToolFile(`http://127.0.0.1:${options.bridgePort}`)

  await mkdir(toolsDir, { recursive: true })
  await writeFile(toolPath, next)
  return [toolPath]
}
