import { mkdir, readFile, unlink, writeFile } from "node:fs/promises"
import { join } from "node:path"

const header = "// Generated by opencode-discord-bot. DO NOT EDIT."
const loopbackUrlPlaceholder = "__OPENCODE_DISCORD_BOT_LOOPBACK_URL__"
const deprecatedDiscordBridgeFiles = ["discord-bridge.ts", "discord-fetch-history.ts"] as const

const discordToolSources = [
  { fileName: "discord-add-reaction.ts", sourceUrl: new URL("./DiscordAddReactionTool.ts", import.meta.url) },
  { fileName: "discord-search-messages.ts", sourceUrl: new URL("./DiscordSearchMessagesTool.ts", import.meta.url) },
  { fileName: "discord-attach-file.ts", sourceUrl: new URL("./DiscordAttachFileTool.ts", import.meta.url) },
  { fileName: "discord-create-thread.ts", sourceUrl: new URL("./DiscordCreateThreadTool.ts", import.meta.url) }
] as const

export type ToolScaffoldOptions = {
  readonly projectDir: string
  readonly bridgePort: number
  readonly enabled: boolean
  readonly autoInstall: boolean
}

const isMissingFile = (cause: unknown): boolean => typeof cause === "object" && cause !== null && "code" in cause && cause.code === "ENOENT"

const removeDeprecatedGeneratedTool = async (toolsDir: string): Promise<void> => {
  for (const fileName of deprecatedDiscordBridgeFiles) {
    const toolPath = join(toolsDir, fileName)
    try {
      const current = await readFile(toolPath, "utf8")
      if (current.startsWith(header)) await unlink(toolPath)
    } catch (cause) {
      if (!isMissingFile(cause)) throw cause
    }
  }
}

export const renderDiscordToolFile = async (sourceUrl: URL, loopbackUrl: string): Promise<string> => {
  const source = await readFile(sourceUrl, "utf8")
  return `${header}\n${source.replaceAll(loopbackUrlPlaceholder, loopbackUrl)}`
}

export const ensureDiscordTools = async (options: ToolScaffoldOptions): Promise<ReadonlyArray<string>> => {
  if (!options.enabled || !options.autoInstall) return []
  const toolsDir = join(options.projectDir, ".opencode", "tools")
  const loopbackUrl = `http://127.0.0.1:${options.bridgePort}`

  await mkdir(toolsDir, { recursive: true })
  await removeDeprecatedGeneratedTool(toolsDir)

  const toolPaths: Array<string> = []
  for (const source of discordToolSources) {
    const toolPath = join(toolsDir, source.fileName)
    const next = await renderDiscordToolFile(source.sourceUrl, loopbackUrl)
    await writeFile(toolPath, next)
    toolPaths.push(toolPath)
  }
  return toolPaths
}
