import { describe, expect, test } from "bun:test"
import { mkdir, mkdtemp, readFile, rm, writeFile } from "node:fs/promises"
import { tmpdir } from "node:os"
import { join } from "node:path"
import { ensureDiscordTools, renderDiscordToolFile } from "./Scaffolding.ts"

describe("Discord tool scaffolding", () => {
  test("renders a generated tool file with the injected loopback URL", () => {
    const source = renderDiscordToolFile("http://127.0.0.1:8787")

    expect(source).toContain("Generated by opencode-discord-bot")
    expect(source).toContain("http://127.0.0.1:8787/tool")
    expect(source).toContain("fetch")
  })

  test("creates and refreshes only generated files", async () => {
    const projectDir = await mkdtemp(join(tmpdir(), "ocdb-tools-"))

    try {
      const created = await ensureDiscordTools({ projectDir, bridgePort: 8787, enabled: true, autoInstall: true })
      const toolPath = join(projectDir, ".opencode", "tools", "discord-bridge.ts")
      const first = await readFile(toolPath, "utf8")

      expect(created).toEqual([toolPath])
      expect(first).toContain("http://127.0.0.1:8787/tool")

      await ensureDiscordTools({ projectDir, bridgePort: 9999, enabled: true, autoInstall: true })
      expect(await readFile(toolPath, "utf8")).toContain("http://127.0.0.1:9999/tool")

      await writeFile(toolPath, "// operator file\n")
      const skipped = await ensureDiscordTools({ projectDir, bridgePort: 7777, enabled: true, autoInstall: true })

      expect(skipped).toEqual([])
      expect(await readFile(toolPath, "utf8")).toBe("// operator file\n")

      await writeFile(toolPath, `${renderDiscordToolFile("http://127.0.0.1:9999")}\n// operator edit\n`)
      const edited = await ensureDiscordTools({ projectDir, bridgePort: 6666, enabled: true, autoInstall: true })

      expect(edited).toEqual([])
      expect(await readFile(toolPath, "utf8")).toContain("// operator edit")
    } finally {
      await rm(projectDir, { recursive: true, force: true })
    }
  })

  test("does nothing when auto install is disabled", async () => {
    const projectDir = await mkdtemp(join(tmpdir(), "ocdb-tools-disabled-"))

    try {
      await mkdir(join(projectDir, ".opencode"), { recursive: true })
      expect(await ensureDiscordTools({ projectDir, bridgePort: 8787, enabled: true, autoInstall: false })).toEqual([])
    } finally {
      await rm(projectDir, { recursive: true, force: true })
    }
  })
})
