import { describe, expect, test } from "bun:test"
import { mkdir, mkdtemp, readFile, rm, stat, writeFile } from "node:fs/promises"
import { tmpdir } from "node:os"
import { join } from "node:path"
import { ensureDiscordTools, renderDiscordToolFile } from "./Scaffolding.ts"

const toolFiles = ["discord-add-reaction.ts", "discord-fetch-history.ts", "discord-attach-file.ts", "discord-create-thread.ts"] as const

const sourceUrls = [
  new URL("./DiscordAddReactionTool.ts", import.meta.url),
  new URL("./DiscordFetchHistoryTool.ts", import.meta.url),
  new URL("./DiscordAttachFileTool.ts", import.meta.url),
  new URL("./DiscordCreateThreadTool.ts", import.meta.url)
] as const

const exists = async (path: string): Promise<boolean> =>
  stat(path).then(
    () => true,
    () => false
  )

describe("Discord tool scaffolding", () => {
  test("renders generated split opencode tool files with typed action arguments", async () => {
    const sources = await Promise.all(sourceUrls.map((sourceUrl) => renderDiscordToolFile(sourceUrl, "http://127.0.0.1:8787")))
    const combined = sources.join("\n")

    for (const source of sources) {
      expect(source).toContain("Generated by opencode-discord-bot")
      expect(source).toContain("http://127.0.0.1:8787/tool")
      expect(source).toContain('import { tool } from "@opencode-ai/plugin"')
      expect(source).toContain("export default tool({")
      expect(source).toContain("target: targetSchema")
      expect(source).toContain("fetch")
      expect(source).not.toContain("export const parameters")
      expect(source).not.toContain("__OPENCODE_DISCORD_BOT_LOOPBACK_URL__")
      expect(source).not.toContain("tool.schema.unknown")
      expect(source).not.toContain(".record(")
    }

    expect(combined).toContain('action: "addReaction"')
    expect(combined).toContain('action: "fetchHistory"')
    expect(combined).toContain('action: "attachFile"')
    expect(combined).toContain('action: "createThread"')
    expect(combined).toContain("emoji:")
    expect(combined).toContain("limit:")
    expect(combined).toContain("path:")
    expect(combined).toContain("name:")
    expect(combined).not.toContain("removeReaction")
    expect(combined).not.toContain("editOwnMessage")
    expect(combined).not.toContain("deleteOwnMessage")
    expect(combined).not.toContain('action: "pin"')
    expect(combined).not.toContain('action: "unpin"')
  })

  test("creates and regenerates split tool files on every run", async () => {
    const projectDir = await mkdtemp(join(tmpdir(), "ocdb-tools-"))

    try {
      const created = await ensureDiscordTools({ projectDir, bridgePort: 8787, enabled: true, autoInstall: true })
      const toolPaths = toolFiles.map((file) => join(projectDir, ".opencode", "tools", file))
      const first = await readFile(toolPaths[0] ?? "", "utf8")

      expect(created).toEqual(toolPaths)
      expect(first).toContain("http://127.0.0.1:8787/tool")

      await ensureDiscordTools({ projectDir, bridgePort: 9999, enabled: true, autoInstall: true })
      for (const toolPath of toolPaths) expect(await readFile(toolPath, "utf8")).toContain("http://127.0.0.1:9999/tool")

      await writeFile(toolPaths[0] ?? "", "// operator file\n")
      const regenerated = await ensureDiscordTools({ projectDir, bridgePort: 7777, enabled: true, autoInstall: true })

      expect(regenerated).toEqual(toolPaths)
      expect(await readFile(toolPaths[0] ?? "", "utf8")).toContain("http://127.0.0.1:7777/tool")
      expect(await readFile(toolPaths[0] ?? "", "utf8")).not.toContain("// operator file")

      const deprecatedToolPath = join(projectDir, ".opencode", "tools", "discord-bridge.ts")
      await writeFile(deprecatedToolPath, "// Generated by opencode-discord-bot. DO NOT EDIT.\nexport const parameters = {}\n")
      const migrated = await ensureDiscordTools({ projectDir, bridgePort: 6666, enabled: true, autoInstall: true })

      expect(migrated).toEqual(toolPaths)
      for (const toolPath of toolPaths) expect(await readFile(toolPath, "utf8")).toContain("http://127.0.0.1:6666/tool")
      expect(await exists(deprecatedToolPath)).toBe(false)
    } finally {
      await rm(projectDir, { recursive: true, force: true })
    }
  })

  test("does nothing when auto install is disabled", async () => {
    const projectDir = await mkdtemp(join(tmpdir(), "ocdb-tools-disabled-"))

    try {
      await mkdir(join(projectDir, ".opencode"), { recursive: true })
      expect(await ensureDiscordTools({ projectDir, bridgePort: 8787, enabled: true, autoInstall: false })).toEqual([])
    } finally {
      await rm(projectDir, { recursive: true, force: true })
    }
  })
})
